[EMAIL]
provider = outlook
smtp_server = smtp.office365.com
smtp_port = 587
sender_email = 
sender_password = 

# Primary recipients
recipient_emails = dhananjani.d@algospring.com

# Carbon copy recipients
cc_emails = aruni.j@algospring.com

# Blind carbon copy recipients
bcc_emails = thevindu.r@algospring.com

send_emails = true

[OPTIONS]
# how many recent log lines to include in error emails
log_tail_lines = 200
